### ISSUE TITLE
Segmentation Fault while at startup when the package is enabled

### ISSUE THREAD

**Issue by mr-ubik** [cmur2/language-terraform#33]
Hi there, I tried to install your package but it seems to cause my Atom to freeze and crash during startup. I will try and test whether I can reproduce the issue with a bare setup.

**Comment by tech-vsilva** [comment]
The same here. I'm using it on Ubuntu 16.04.

**Comment by cmur2** [comment]
I'd like to collect more insight on this issue in https://github.com/cmur2/language-terraform/issues/41 as it definitely does not affect every user equally and although there is a possible culprit it's not easy to say which factors (like possibly other installed Atom package etc) contribute to this.
