### ISSUE TITLE
Maps Flagged as Error 

### ISSUE THREAD

**Issue by darkn3rd** [cmur2/language-terraform#37]
## Summary 

A nested map is flagged as an error.  The curly brace after network_policy_config is highlight as red.

```hcl
resource "google_container_cluster" "testbook" {
  name               = "testbook"
  zone               = "us-east1-b"
  initial_node_count = 3

  addons_config {
    network_policy_config {
      disabled = true
    }
  }
}
```

## Example
<img width="283" alt="hcl_error_example" src="https://user-images.githubusercontent.com/7537882/40815284-40ee90ba-64fa-11e8-842c-ba9da14cfa56.png">

**Comment by cmur2** [comment]
In v0.9.3 of this package this is working correctly now so I will close the issue. Please reopen if you spot the problem again.
