### ISSUE TITLE
Add terraform 0.12 support

### ISSUE THREAD

**Issue by lazouz** [cmur2/language-terraform#42]
Hi, 

Terraform 0.12 is out, and the grammar has changed a little bit.

see https://www.terraform.io/docs/configuration/syntax.html

It would be great to update this package accordingly !

**Comment by AndrewFarley** [comment]
+1 - 6 months later since creation we still need this

**Comment by Prophet32j** [comment]
+1

**Comment by cmur2** [comment]
As I really wanted to get syntax highlighting for Terraform 0.12 features and did not want to wait any longer I hacked something together based on the current grammar (left old grammar, right new):

![image (4)](https://user-images.githubusercontent.com/800933/75035079-ef0ef900-54ae-11ea-856f-5b39e876836c.png)

To be able to use the new grammar now I forked this repository (as contributions from PRs are not getting merged in the last year) to https://github.com/cmur2/language-terraform-12 and created a new Atom package [`language-terraform-12`](https://atom.io/packages/language-terraform-12):
```
apm uninstall language-terraform && apm install language-terraform-12
```

**I would be more than happy to upstream my changes into this (the original) package that is soo useful if the maintainer wants to :slightly_smiling_face:**

**Comment by GiantToast** [comment]
Hi @cmur2 I sent you an email about possibly taking over this repo.  I haven't had the time in quite a while now to give this the attention it deserves and would love to find it a new home.

**Comment by lazouz** [comment]
great !

**Comment by cmur2** [comment]
For transparency: the maintainer changed now, see https://github.com/cmur2/language-terraform/issues/46 for more details including next steps.

**Comment by cmur2** [comment]
Closing since most important TF 0.12 syntax features done via https://github.com/cmur2/language-terraform/commit/45a9b38091510ee66c222e4e11e06e83ad08ce87 and https://github.com/cmur2/language-terraform/commit/86289aa95ecfa539b265eeb210793ed6cd35bc1e - there is certainly room for more, happy to accept contributions!
