### ISSUE TITLE
language-terraform breaks language-todo

### ISSUE THREAD

**Issue by agrrh** [cmur2/language-terraform#52]
Sadly, I can't use TODOs in my TF code anymore.

Terraform language:

![Screenshot from 2020-11-26 18-37-18](https://user-images.githubusercontent.com/1294495/100369856-81cc5d80-3016-11eb-8265-6262e3593249.png)

Any other language, YAML in this case:

![Screenshot from 2020-11-26 18-37-30](https://user-images.githubusercontent.com/1294495/100369859-8264f400-3016-11eb-9fc2-b20660053000.png)

Just to mention, toggling "Use tree sitter parsers" option makes no effect.

**Comment by cmur2** [comment]
Thanks for the report @agrrh, do you know if this is a new problem or was that always like this? I'm looking into how other languages do this, happy for any pointers (out of tree).

**Comment by cmur2** [comment]
Guess I found a pointer https://github.com/atom/language-yaml/pull/90 to how this could be done https://github.com/atom/language-coffee-script/commit/ad0aa553d8f91ca1c4605da0bce5bcaf66c3e2bd

**Comment by cmur2** [comment]
I released v0.9.6 with a fix for your problem, please check if it works for you now :)

**Comment by agrrh** [comment]
It works awesome, thank you!
